// <auto-generated />
using System;
using HotelWebsiteBuilder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelWebsiteBuilder.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250729224109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelWebsiteBuilder.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AmenitiesJson")
                        .HasColumnType("text");

                    b.Property<string>("CheckInTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckOutTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Facebook")
                        .HasColumnType("text");

                    b.Property<string>("FacilitiesJson")
                        .HasColumnType("text");

                    b.Property<string>("GalleryImage1")
                        .HasColumnType("text");

                    b.Property<string>("GalleryImage2")
                        .HasColumnType("text");

                    b.Property<string>("GalleryImage3")
                        .HasColumnType("text");

                    b.Property<string>("GalleryImage4")
                        .HasColumnType("text");

                    b.Property<string>("GalleryImage5")
                        .HasColumnType("text");

                    b.Property<string>("GalleryImagesJson")
                        .HasColumnType("text");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("text");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("text");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pricing")
                        .HasColumnType("text");

                    b.Property<string>("RoomTypes")
                        .HasColumnType("text");

                    b.Property<string>("RoomsJson")
                        .HasColumnType("text");

                    b.Property<string>("SliderImagesJson")
                        .HasColumnType("text");

                    b.Property<int>("StarRating")
                        .HasColumnType("integer");

                    b.Property<string>("Twitter")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<string>("YouTube")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hotels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Sultanahmet Meydanı No:1, İstanbul, Türkiye",
                            AmenitiesJson = "[\"\\u00DCcretsiz Wi-Fi\",\"Spa \\u0026 Wellness\",\"Restoran\",\"Bar\",\"Havuz\",\"Fitness Merkezi\",\"Oda Servisi\",\"Valet Parking\",\"Konferans Salonu\"]",
                            CheckInTime = "14:00",
                            CheckOutTime = "12:00",
                            CreatedAt = new DateTime(2025, 7, 29, 22, 41, 9, 444, DateTimeKind.Utc).AddTicks(7770),
                            Currency = "TRY",
                            Description = "İstanbul'un kalbinde, tarihi yarımadada konumlanan lüks otelimizde unutulmaz bir konaklama deneyimi yaşayın.",
                            Email = "info@grandistanbul.com",
                            Facebook = "https://facebook.com/grandistanbulhotel",
                            FacilitiesJson = "[{\"Name\":\"Spa \\u0026 Wellness\",\"Description\":\"Rahatlat\\u0131c\\u0131 spa hizmetleri ve wellness merkezi\",\"Icon\":\"spa-icon.png\",\"IsAvailable\":true},{\"Name\":\"Restoran\",\"Description\":\"Geleneksel ve modern lezzetlerin bulu\\u015Ftu\\u011Fu restoran\",\"Icon\":\"restaurant-icon.png\",\"IsAvailable\":true},{\"Name\":\"Havuz\",\"Description\":\"Kapal\\u0131 ve a\\u00E7\\u0131k havuz se\\u00E7enekleri\",\"Icon\":\"pool-icon.png\",\"IsAvailable\":true},{\"Name\":\"Fitness Merkezi\",\"Description\":\"Modern ekipmanlarla donat\\u0131lm\\u0131\\u015F fitness merkezi\",\"Icon\":\"fitness-icon.png\",\"IsAvailable\":true}]",
                            GalleryImage1 = "https://via.placeholder.com/800x600?text=Istanbul+View",
                            GalleryImage2 = "https://via.placeholder.com/800x600?text=Hotel+Lobby",
                            GalleryImage3 = "https://via.placeholder.com/800x600?text=Deluxe+Room",
                            GalleryImage4 = "https://via.placeholder.com/800x600?text=Restaurant",
                            GalleryImage5 = "https://via.placeholder.com/800x600?text=Spa+Center",
                            GalleryImagesJson = "[\"https://via.placeholder.com/800x600?text=Istanbul\\u002BView\",\"https://via.placeholder.com/800x600?text=Hotel\\u002BLobby\",\"https://via.placeholder.com/800x600?text=Deluxe\\u002BRoom\",\"https://via.placeholder.com/800x600?text=Restaurant\",\"https://via.placeholder.com/800x600?text=Spa\\u002BCenter\"]",
                            HotelName = "Grand Istanbul Hotel",
                            Instagram = "https://instagram.com/grandistanbulhotel",
                            Language = "tr",
                            Latitude = 41.008200000000002,
                            LinkedIn = "https://linkedin.com/company/grandistanbulhotel",
                            LogoUrl = "https://via.placeholder.com/200x80?text=Grand+Istanbul",
                            Longitude = 28.978400000000001,
                            MetaDescription = "İstanbul'un kalbinde, tarihi yarımadada konumlanan lüks otelimizde unutulmaz bir konaklama deneyimi yaşayın.",
                            MetaKeywords = "istanbul, otel, lüks, sultanahmet, konaklama, spa, restoran",
                            MetaTitle = "Grand Istanbul Hotel - İstanbul'daki Lüks Otel",
                            Phone = "+90 212 555 0123",
                            Pricing = "Standart: 1200 TL/gece, Deluxe: 1800 TL/gece, Süit: 2800 TL/gece, Başkanlık: 5000 TL/gece",
                            RoomTypes = "Standart Oda, Deluxe Oda, Süit Oda, Başkanlık Süiti",
                            RoomsJson = "[{\"Type\":\"Standart Oda\",\"Description\":\"Konforlu ve \\u015F\\u0131k standart odalar\\u0131m\\u0131zda rahat bir konaklama deneyimi.\",\"Price\":1200,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"Wi-Fi\"],\"Images\":[\"standart1.jpg\",\"standart2.jpg\"],\"Capacity\":2,\"IsAvailable\":true},{\"Type\":\"Deluxe Oda\",\"Description\":\"Geni\\u015F ve l\\u00FCks deluxe odalar\\u0131m\\u0131zda \\u015Fehir manzaras\\u0131 e\\u015Fli\\u011Finde konaklama.\",\"Price\":1800,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"Wi-Fi\",\"\\u015Eehir Manzaras\\u0131\"],\"Images\":[\"deluxe1.jpg\",\"deluxe2.jpg\"],\"Capacity\":2,\"IsAvailable\":true},{\"Type\":\"S\\u00FCit Oda\",\"Description\":\"L\\u00FCks s\\u00FCit odalar\\u0131m\\u0131zda ayr\\u0131 oturma alan\\u0131 ve jakuzi ile konforlu konaklama.\",\"Price\":2800,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"Wi-Fi\",\"Jakuzi\",\"Oturma Alan\\u0131\"],\"Images\":[\"suit1.jpg\",\"suit2.jpg\"],\"Capacity\":3,\"IsAvailable\":true},{\"Type\":\"Ba\\u015Fkanl\\u0131k S\\u00FCiti\",\"Description\":\"En l\\u00FCks ba\\u015Fkanl\\u0131k s\\u00FCitimizde \\u00F6zel hizmetler ve geni\\u015F alan.\",\"Price\":5000,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"Wi-Fi\",\"Jakuzi\",\"Oturma Alan\\u0131\",\"\\u00D6zel Hizmetler\"],\"Images\":[\"presidential1.jpg\",\"presidential2.jpg\"],\"Capacity\":4,\"IsAvailable\":true}]",
                            SliderImagesJson = "[\"https://via.placeholder.com/1200x600?text=Grand\\u002BIstanbul\\u002BSlider\\u002B1\",\"https://via.placeholder.com/1200x600?text=Grand\\u002BIstanbul\\u002BSlider\\u002B2\",\"https://via.placeholder.com/1200x600?text=Grand\\u002BIstanbul\\u002BSlider\\u002B3\"]",
                            StarRating = 5,
                            Twitter = "https://twitter.com/grandistanbul",
                            UpdatedAt = new DateTime(2025, 7, 29, 22, 41, 9, 444, DateTimeKind.Utc).AddTicks(7770),
                            Website = "https://grandistanbul.com",
                            YouTube = "https://youtube.com/grandistanbulhotel"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Konyaaltı Sahili No:15, Antalya, Türkiye",
                            AmenitiesJson = "[\"Deniz Manzaras\\u0131\",\"Havuz\",\"Plaj Eri\\u015Fimi\",\"Su Sporlar\\u0131\",\"Spa\",\"Restoran\",\"Bar\",\"\\u00C7ocuk Kul\\u00FCb\\u00FC\",\"Animasyon\"]",
                            CheckInTime = "15:00",
                            CheckOutTime = "11:00",
                            CreatedAt = new DateTime(2025, 7, 29, 22, 41, 9, 444, DateTimeKind.Utc).AddTicks(8400),
                            Currency = "TRY",
                            Description = "Antalya'nın en güzel sahillerinde, mavi denizin kucakladığı resort otelimizde tatil keyfini yaşayın.",
                            Email = "info@bluesea.com",
                            Facebook = "https://facebook.com/bluesearesort",
                            FacilitiesJson = "[{\"Name\":\"Su Sporlar\\u0131\",\"Description\":\"Dal\\u0131\\u015F, jet ski, parasailing gibi su sporlar\\u0131 aktiviteleri\",\"Icon\":\"water-sports-icon.png\",\"IsAvailable\":true},{\"Name\":\"Spa \\u0026 Wellness\",\"Description\":\"Deniz manzaras\\u0131 e\\u015Fli\\u011Finde spa ve wellness hizmetleri\",\"Icon\":\"spa-icon.png\",\"IsAvailable\":true},{\"Name\":\"\\u00C7ocuk Kul\\u00FCb\\u00FC\",\"Description\":\"\\u00C7ocuklar i\\u00E7in \\u00F6zel aktivite alan\\u0131 ve animasyon\",\"Icon\":\"kids-club-icon.png\",\"IsAvailable\":true},{\"Name\":\"Plaj\",\"Description\":\"\\u00D6zel plaj alan\\u0131 ve \\u015Fezlong hizmeti\",\"Icon\":\"beach-icon.png\",\"IsAvailable\":true}]",
                            GalleryImage1 = "https://via.placeholder.com/800x600?text=Sea+View",
                            GalleryImage2 = "https://via.placeholder.com/800x600?text=Pool+Area",
                            GalleryImage3 = "https://via.placeholder.com/800x600?text=Beach+Access",
                            GalleryImage4 = "https://via.placeholder.com/800x600?text=Water+Sports",
                            GalleryImage5 = "https://via.placeholder.com/800x600?text=Sunset+Bar",
                            GalleryImagesJson = "[\"https://via.placeholder.com/800x600?text=Sea\\u002BView\",\"https://via.placeholder.com/800x600?text=Pool\\u002BArea\",\"https://via.placeholder.com/800x600?text=Beach\\u002BAccess\",\"https://via.placeholder.com/800x600?text=Water\\u002BSports\",\"https://via.placeholder.com/800x600?text=Sunset\\u002BBar\"]",
                            HotelName = "Blue Sea Resort",
                            Instagram = "https://instagram.com/bluesearesort",
                            Language = "tr",
                            Latitude = 36.896900000000002,
                            LinkedIn = "https://linkedin.com/company/bluesearesort",
                            LogoUrl = "https://via.placeholder.com/200x80?text=Blue+Sea",
                            Longitude = 30.7133,
                            MetaDescription = "Antalya'nın en güzel sahillerinde, mavi denizin kucakladığı resort otelimizde tatil keyfini yaşayın.",
                            MetaKeywords = "antalya, resort, deniz, plaj, tatil, spa, su sporları",
                            MetaTitle = "Blue Sea Resort - Antalya'daki Resort Otel",
                            Phone = "+90 242 555 0456",
                            Pricing = "Deniz Manzaralı: 1500 TL/gece, Aile: 2200 TL/gece, Villa: 3500 TL/gece, Başkanlık: 6000 TL/gece",
                            RoomTypes = "Deniz Manzaralı Oda, Aile Odası, Villa, Başkanlık Villa",
                            RoomsJson = "[{\"Type\":\"Deniz Manzaral\\u0131 Oda\",\"Description\":\"Masmavi deniz manzaras\\u0131 e\\u015Fli\\u011Finde konforlu konaklama.\",\"Price\":1500,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"Deniz Manzaras\\u0131\",\"Balkon\"],\"Images\":[\"sea-view1.jpg\",\"sea-view2.jpg\"],\"Capacity\":2,\"IsAvailable\":true},{\"Type\":\"Aile Odas\\u0131\",\"Description\":\"Geni\\u015F aile odalar\\u0131m\\u0131zda \\u00E7ocuklar\\u0131n\\u0131zla birlikte rahat konaklama.\",\"Price\":2200,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"\\u0130ki Yatak\",\"\\u00C7ocuk K\\u00F6\\u015Fesi\"],\"Images\":[\"family1.jpg\",\"family2.jpg\"],\"Capacity\":4,\"IsAvailable\":true},{\"Type\":\"Villa\",\"Description\":\"\\u00D6zel villalar\\u0131m\\u0131zda l\\u00FCks ve konfor bir arada.\",\"Price\":3500,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"\\u00D6zel Havuz\",\"Bah\\u00E7e\"],\"Images\":[\"villa1.jpg\",\"villa2.jpg\"],\"Capacity\":6,\"IsAvailable\":true},{\"Type\":\"Ba\\u015Fkanl\\u0131k Villa\",\"Description\":\"En l\\u00FCks ba\\u015Fkanl\\u0131k villam\\u0131zda \\u00F6zel hizmetler.\",\"Price\":6000,\"Features\":[\"Klima\",\"TV\",\"Mini bar\",\"\\u00D6zel Havuz\",\"Bah\\u00E7e\",\"\\u00D6zel Hizmetler\"],\"Images\":[\"presidential-villa1.jpg\",\"presidential-villa2.jpg\"],\"Capacity\":8,\"IsAvailable\":true}]",
                            SliderImagesJson = "[\"https://via.placeholder.com/1200x600?text=Blue\\u002BSea\\u002BSlider\\u002B1\",\"https://via.placeholder.com/1200x600?text=Blue\\u002BSea\\u002BSlider\\u002B2\",\"https://via.placeholder.com/1200x600?text=Blue\\u002BSea\\u002BSlider\\u002B3\"]",
                            StarRating = 4,
                            Twitter = "https://twitter.com/bluesea",
                            UpdatedAt = new DateTime(2025, 7, 29, 22, 41, 9, 444, DateTimeKind.Utc).AddTicks(8400),
                            Website = "https://bluesea.com",
                            YouTube = "https://youtube.com/bluesearesort"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
